### ISSUE TITLE
File missing during compilation

### ISSUE THREAD

**Issue by Tokn59** [MarcFinns/AtmoScan#5]
During compilation of the Atmoscan 1.4 sketch the following error is produced : 
sketch\esp32-hal-i2c.c:16:23: fatal error: esp32-hal.h: No such file or directory

 #include "esp32-hal.h"

                       ^

compilation terminated.

Multiple libraries were found for "SD.h"
 Used: C:\Users\Tony\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc2\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
exit status 1
Error compiling for board Generic ESP8266 Module.

Any idea how to solve this ?

Thanks and kind regards,

Tony

**Comment by per1234** [comment]
Why do you have a file named esp32-hal-i2c.c in your sketch folder? There is no file of that name in this repository.

**Comment by MarcFinns** [comment]
Looks like you are compiling for ESP32. This is an ESP8266 project. You should compile against NodeMCU 1.0 with the 4M (2M SPIFFS) option added. All in the instructable
